name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Make gradlew executable
    - name: Grant execute permission for gradlew
      run: chmod +x Hotel-System/gradlew

    # Build the project using Gradle Wrapper
    - name: Build with Gradle Wrapper
      working-directory: Hotel-System
      run: ./gradlew build

    # Run tests using Gradle Wrapper
    - name: Run Tests with Gradle Wrapper
      working-directory: Hotel-System
      run: ./gradlew test

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Make gradlew executable
    - name: Grant execute permission for gradlew
      run: chmod +x Hotel-System/gradlew

    # Generate and submit dependency graph
    - name: Generate and submit dependency graph
      working-directory: Hotel-System
      run: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
